apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-api-entrega
  labels:
    app: dep-api-entrega
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dep-api-entrega
  template:
    metadata:
      labels:
        app: dep-api-entrega
    spec:
      containers:
      - name: dep-api-entrega-container
        image: 308294614673.dkr.ecr.us-east-1.amazonaws.com/entrega:latest
        resources:
          requests:
            cpu: 10m
        ports:
        - containerPort: 3000
        env:
        - name: MARIADB_HOST
          valueFrom:
            secretKeyRef:
              name: db-secrets-api-entrega
              key: MARIADB_HOST
              optional: false
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets-api-entrega
              key: MARIADB_USER
              optional: false
        - name: MARIADB_PASS
          valueFrom:
            secretKeyRef:
              name: db-secrets-api-entrega
              key: MARIADB_PASS
              optional: false
        - name: MARIADB_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-secrets-api-entrega
              key: MARIADB_DATABASE
              optional: false
        - name: MARIADB_PORT
          valueFrom:
            secretKeyRef:
              name: db-secrets-api-entrega
              key: MARIADB_PORT
              optional: false
        - name: MP_URL
          valueFrom:
            secretKeyRef:
              name: db-secrets-api-entrega
              key: MP_URL
              optional: false
        - name: MP_NOTIFICATION_URL
          valueFrom:
            secretKeyRef:
              name: db-secrets-api-entrega
              key: MP_NOTIFICATION_URL
              optional: false
        - name: MP_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: db-secrets-api-entrega
              key: MP_CLIENT_ID
              optional: false
        - name: MP_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: db-secrets-api-entrega
              key: MP_CLIENT_SECRET
              optional: false
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          failureThreshold: 3
          periodSeconds: 10


