apiVersion: v1
kind: Service
metadata:
  name: svc-api-entrega
  labels:
    app: svc-api-entrega
spec:
  type: NodePort
  selector:
    app: dep-api-entrega
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30004
