apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-api-pagamento
  labels:
    app: dep-api-pagamento
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dep-api-pagamento
  template:
    metadata:
      labels:
        app: dep-api-pagamento
    spec:
      containers:
      - name: dep-api-pagamento-container
        image: 308294614673.dkr.ecr.us-east-1.amazonaws.com/pagamento:latest
        resources:
          requests:
            cpu: 10m
        ports:
        - containerPort: 3000
        env:
        - name: DB_MONGO
          valueFrom:
            secretKeyRef:
              name: db-secrets-api-pagamento
              key: DB_MONGO
              optional: false
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: db-secrets-api-pagamento
              key: PORT
              optional: false
        - name: MP_URL
          valueFrom:
            secretKeyRef:
              name: db-secrets-api-pagamento
              key: MP_URL
              optional: false
        - name: MP_NOTIFICATION_URL
          valueFrom:
            secretKeyRef:
              name: db-secrets-api-pagamento
              key: MP_NOTIFICATION_URL
              optional: false
        - name: MP_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: db-secrets-api-pagamento
              key: MP_CLIENT_ID
              optional: false
        - name: MP_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: db-secrets-api-pagamento
              key: MP_CLIENT_SECRET
              optional: false
        - name: AWS_SQS_URL
          valueFrom:
            secretKeyRef:
              name: db-secrets-api-pagamento
              key: AWS_SQS_URL
              optional: false
        - name: AWS_SQS_PEDIDO_PAGAMENTO
          valueFrom:
            secretKeyRef:
              name: db-secrets-api-pagamento
              key: AWS_SQS_PEDIDO_PAGAMENTO
              optional: false
        - name: AWS_SQS_CONFIRMACAO_PAGAMENTO
          valueFrom:
            secretKeyRef:
              name: db-secrets-api-pagamento
              key: AWS_SQS_CONFIRMACAO_PAGAMENTO
              optional: false
        - name: AWS_SQS_CANCELAR_PEDIDO
          valueFrom:
            secretKeyRef:
              name: db-secrets-api-pagamento
              key: AWS_SQS_CANCELAR_PEDIDO
              optional: false
        - name: AWS_SQS_PEDIDO_ENTREGA
          valueFrom:
            secretKeyRef:
              name: db-secrets-api-pagamento
              key: AWS_SQS_PEDIDO_ENTREGA
              optional: false
        - name: AWS_SQS_PEDIDO_ENTREGA_CANCELAR
          valueFrom:
            secretKeyRef:
              name: db-secrets-api-pagamento
              key: AWS_SQS_PEDIDO_ENTREGA_CANCELAR
              optional: false
        - name: AWS_SQS_PEDIDO_FINALIZADO
          valueFrom:
            secretKeyRef:
              name: db-secrets-api-pagamento
              key: AWS_SQS_PEDIDO_FINALIZADO
              optional: false
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: db-secrets-api-pagamento
              key: AWS_ACCESS_KEY_ID
              optional: false
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: db-secrets-api-pagamento
              key: AWS_SECRET_ACCESS_KEY
              optional: false
        - name: DEBUG
          valueFrom:
            secretKeyRef:
              name: db-secrets-api-pagamento
              key: DEBUG
              optional: false
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          failureThreshold: 3
          periodSeconds: 10


