apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-api-pagamento
spec:
  type: LoadBalancer
  selector:
    app: dep-api-pagamento
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
