apiVersion: v1
kind: Secret
metadata:
  name: db-secrets-api-pagamento
type: Opaque
data:
  MP_URL: aHR0cHM6Ly9hcGkubWVyY2Fkb3BhZ28uY29tL3YxLw==
  MP_NOTIFICATION_URL: aHR0cHM6Ly9nb29nbGUuY29tLmJyLw==
  MP_CLIENT_ID: VEVTVC00MjdmOGU4Yy1kNmNhLTQwMDAtYWI5Yi05NWIzYTJlNTU0Zjc=
  MP_CLIENT_SECRET: VEVTVC04OTI2NDQ1MTIzOTUwMDk3LTAxMTMwNy1lZTVkYzUwYmY1M2MzOGEwMzNmZTVkYTRjOWFjYzljMV9fTERfTEJfXy0yMDkxOTE0NjM=
  DB_MONGO: bW9uZ29kYjovL2ZpYXBtb25nb2RiOkFxdTFOYWRhUGFzc2FyI0Bkb2N1bWVudC1kYi1wZWRpZG9zLWZpYXAtY2x1c3Rlci5jbHVzdGVyLWMzNmVzaTRheTFwMC51cy1lYXN0LTEuZG9jZGIuYW1hem9uYXdzLmNvbToyNzAxNy8/cmVwbGljYVNldD1yczAmcmVhZFByZWZlcmVuY2U9c2Vjb25kYXJ5UHJlZmVycmVkJnJldHJ5V3JpdGVzPWZhbHNl
  DNS: VEVTVEU=
  PORT: MzAwMA==
  AWS_SQS_URL: aHR0cHM6Ly9zcXMudXMtZWFzdC0xLmFtYXpvbmF3cy5jb20vMzA4Mjk0NjE0NjczLw==
  AWS_SQS_PEDIDO_PAGAMENTO: cGVkaWRvcy1wYWdhbWVudG9zLmZpZm8=
  AWS_SQS_CONFIRMACAO_PAGAMENTO: Y29uZmlybWFjYW8tcGFnYW1lbnRvLmZpZm8=
  AWS_SQS_CANCELAR_PEDIDO: Y2FuY2VsYXItcGVkaWRvLmZpZm8=
  AWS_SQS_PEDIDO_ENTREGA: cGVkaWRvLWVudHJlZ2EuZmlmbw==
  AWS_SQS_PEDIDO_ENTREGA_CANCELAR: cGVkaWRvLWVudHJlZ2EtY2FuY2VsYXIuZmlmbw==
  AWS_SQS_PEDIDO_FINALIZADO: cGVkaWRvcy1maW5hbGl6YWRvLmZpZm8=
  DEBUG: ZmFsc2U=
