apiVersion: v1
kind: Service
metadata:
  name: svc-api-pagamento
  labels:
    app: svc-api-pagamento
spec:
  type: NodePort
  selector:
    app: dep-api-pagamento
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30003
