apiVersion: v1
kind: Service
metadata:
  name: svc-db
  labels:
    app: svc-db
spec:
  type: NodePort
  selector:
    app: db-deployment
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
    nodePort: 30336