apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-api
  labels:
    app: dep-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dep-api
  template:
    metadata:
      labels:
        app: dep-api
    spec:
      containers:
      - name: dep-api-container
        image: bruno01/fiap01:latest
        resources:
          requests:
            cpu: 10m
        ports:
        - containerPort: 3000
        env:
          - name: MARIADB_HOST
            value: svc-db
          - name: MARIADB_USER
            value: root
          - name: MARIADB_PASS
            value : qwe1234
          - name: MARIADB_DATABASE
            value: projeto-pedidos
          - name: MARIADB_PORT
            value: "3306"
          - name: MP_URL
            value: "https://api.mercadopago.com/v1/"
          - name: MP_NOTIFICATION_URL
            value: "https://google.com.br/"
          - name: MP_CLIENT_ID
            value: "TEST-427f8e8c-d6ca-4000-ab9b-95b3a2e554f7"
          - name: MP_CLIENT_SECRET
            value: "TEST-8926445123950097-011307-ee5dc50bf53c38a033fe5da4c9acc9c1__LD_LB__-209191463"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          failureThreshold: 3
          periodSeconds: 10
          

