# This is a basic workflow to help you get started with Actions
name: CD deploy kubernets

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "dev", "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: envs_app

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - 
        name: Install kubectl
        uses: azure/setup-kubectl@v2.0
        with:
          version: 'v1.24.0' # default is latest stable
        id: install

      - 
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:  ${{ vars.AWS_REGION }}
          
      - 
        name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - 
        name: PULL docker image
        env:
          IMAGE: bruno01/fiap01:${{ github.event.inputs.docker_hub_tag }}
        run: |
          docker pull $IMAGE
      - 
        name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: producao
          IMAGE: bruno01/fiap01:${{ github.event.inputs.docker_hub_tag }}
        run: |
          docker tag $IMAGE $REGISTRY/$REPOSITORY:${{ github.event.inputs.docker_hub_tag }}
          docker push $REGISTRY/$REPOSITORY:${{ github.event.inputs.docker_hub_tag }}
      
      - 
        name: Update kube config
        env:
          CLUSTER: fiap-cluster
          REGION:  ${{ vars.AWS_REGION }}
        run: aws eks --region $REGION update-kubeconfig --name $CLUSTER
        
      - 
        name: Deploy to EKS 
        env:
          IMAGE: ${{ steps.login-ecr.outputs.registry }}/producao:${{ github.event.inputs.docker_hub_tag }}
        run: |
          echo image $IMAGE
          kubectl apply -f web_cafeteria
